# Generated by Django 6.0.3 on 2026-03-24 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Aberta', 'ABERTA'), ('EM_ANDAMENTO', 'Em andamento'), ('Concluída', 'CONCLUIDA'), ('CANCELADA', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
