# Generated by Django 6.0.3 on 2026-03-24 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0002_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('Concluída', 'CONCLUIDA'), ('Cancelada', 'CANCELADA'), ('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
