# Generated by Django 6.0.3 on 2026-04-20 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0005_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('CONCLUIDA', 'Concluída'), ('Cancelada', 'CANCELADA'), ('URGENTE', 'Urgente'), ('Cancelada', 'NAO_URGENTE')], default='ABERTA', max_length=20),
        ),
    ]
