# Generated by Django 6.0.3 on 2026-04-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0007_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Aberta', 'ABERTA'), ('Em andamento', 'EM_ANDAMENTO'), ('CONCLUIDA', 'Concluída'), ('CANCELADA', 'Cancelada'), ('Urgente', 'URGENTE'), ('NAO_URGENTE', 'Cancelada')], default='ABERTA', max_length=20),
        ),
    ]
