# Generated by Django 6.0.3 on 2026-04-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0009_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Aberta', 'ABERTA'), ('EM_ANDAMENTO', 'Em andamento'), ('Concluída', 'CONCLUIDA'), ('Cancelada', 'CANCELADA'), ('Urgente', 'URGENTE'), ('Cancelada', 'NAO_URGENTE')], default='ABERTA', max_length=20),
        ),
    ]
