# Generated by Django 6.0.3 on 2026-04-20 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0010_alter_tarefa_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('Em andamento', 'EM_ANDAMENTO'), ('CONCLUIDA', 'Concluída'), ('Cancelada', 'CANCELADA'), ('Urgente', 'URGENTE'), ('Cancelada', 'NAO_URGENTE')], default='ABERTA', max_length=20),
        ),
    ]
