# Generated by Django 6.0.3 on 2026-04-20 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0011_alter_tarefa_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('Aberta', 'ABERTA'), ('EM_ANDAMENTO', 'Em andamento'), ('Concluída', 'CONCLUIDA'), ('Cancelada', 'CANCELADA'), ('URGENTE', 'Urgente'), ('Cancelada', 'NAO_URGENTE')], default='ABERTA', max_length=20),
        ),
    ]
