# Generated by Django 6.0.3 on 2026-04-20 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0012_tarefa_usuario_responsavel_alter_tarefa_status'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em andamento'), ('Concluída', 'CONCLUIDA'), ('CANCELADA', 'Cancelada'), ('URGENTE', 'Urgente'), ('NAO_URGENTE', 'Cancelada')], default='ABERTA', max_length=20),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='usuario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios', to='usuarios.usuario'),
        ),
    ]
